-- MySQL Script generated by MySQL Workbench
-- Tue Dec  4 13:05:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dilog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dilog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dilog` DEFAULT CHARACTER SET utf8 ;
USE `dilog` ;

-- -----------------------------------------------------
-- Table `dilog`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dilog`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `username_UNIQUE_user` (`username` ASC),
  UNIQUE INDEX `ID_UNIQUE_user` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dilog`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dilog`.`Post` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  `Content` LONGTEXT NOT NULL,
  `Category` VARCHAR(35) NULL,
  `isPrivate` TINYINT NOT NULL,
  `LastEdit` DATETIME NULL,
  UNIQUE INDEX `ID_UNIQUE_Post` (`ID` ASC),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dilog`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dilog`.`Comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PostID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `Message` VARCHAR(255) NOT NULL,
  `LastEdit` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE_Comments` (`ID` ASC),
  INDEX `PostID_comments` (`PostID` ASC),
  CONSTRAINT `comments_PostID`
    FOREIGN KEY (`PostID`)
    REFERENCES `dilog`.`Post` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dilog`.`SharedPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dilog`.`SharedPost` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PostID` INT NOT NULL,
  `Owner` VARCHAR(45) NOT NULL,
  `Viewer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE_Shared` (`ID` ASC),
  INDEX `PostID_Shared` (`PostID` ASC),
  CONSTRAINT `sharedpost_PostID`
    FOREIGN KEY (`PostID`)
    REFERENCES `dilog`.`Post` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
